repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.1.1  # Use the ref you want to point at
    hooks:
      - id: flake8
        language_version: python3.7
