language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - pip install codecov

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
  - docker-compose run app sh -c "coverage run manage.py test"

# Push the results back to codecov
after_success:
  - codecov
