language: python
python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose

script:
  - docker-compose run backend sh -c "python manage.py test && flake8"
  - docker-compose run backend sh -c "coverage run manage.py test"
  - docker-compose run -e CODECOV_TOKEN=${CODECOV_TOKEN} backend sh -c "bash <(curl -s https://codecov.io/bash)"