version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "5678:5678"
    user: root
    volumes:
      - ./app/:/app
    command: >
      sh -c "pip install ptvsd &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python -m ptvsd --host 0.0.0.0 --port 5678 --wait manage.py runserver 0.0.0.0:8000 --noreload"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecret
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
